/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nihao' at '17-6-14 上午11:24' with Gradle 2.11
 *
 * @author nihao, @date 17-6-14 上午11:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
